"""asdl2jac - emit Jac AST node archetypes from CPython's Python.asdl.

This generator reuses
CPython's own ASDL parser (reference/cpython/Parser/asdl.py) to read the frozen
DSL, then emits jacpython's AST node object model. Regenerate whenever the
pinned CPython tag moves (see tools/fetch_cpython_reference.py).

Usage:
    python jac-py/tools/asdl2jac.py            # writes jac-py/jacpython/ast_nodes.jac
    python jac-py/tools/asdl2jac.py --stdout   # print to stdout

Mapping:
  - every archetype shares a single root `obj ast_node {}` so generic
    AST-holding seams (parser memo tables, `list[stmt]`, pass dispatch) type
    against one root; concrete-node dispatch in the compiler is `isinstance`
    if-chains (the sanctioned na-clean PYOBJ_TYPES pattern - a `kind`-int field
    is not viable: Jac silently ignores a subclass `has` default override).
  - ASDL builtin types:  identifier/string -> str, int -> int, constant -> PyObj
    (literal values are leaf objects - PyInt/PyStr/PyNone/... - not host `any`,
    so the na-clean pipeline and flowgraph const-folding stay typed)
  - sum type T          -> base `obj T(ast_node) {}` + one `obj C(T) {...}` per constructor
  - product type P      -> `obj P(ast_node) {...}` (single anonymous constructor)
  - simple sum (enums)  -> base + empty singleton-shaped subclasses
  - field `T`           -> has name: T
  - field `T?`          -> has name: T | None
  - field `T*`          -> has name: list[T]   (list[T | None] if also optional)
  - a sum's `attributes` are appended as fields to every constructor of that sum

Known limitation (2 fields): `match_case.pattern` and `MatchAs.pattern` are
named `pattern` and typed `pattern`. Jac resolves a `has` field's own annotation
in a scope where the field name shadows the same-named type, so the checker marks
those two annotations Unknown (a W1051 warning, not an error). Construction and
runtime are unaffected; only static typing of `.pattern` is lost. Names are kept
faithful to CPython's AST on purpose. The clean fix (a self-import type alias) is
a runtime circular-import hazard, so it is deliberately not used here.
"""

from __future__ import annotations

import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_REPO = os.path.dirname(os.path.dirname(_HERE))
_CPY_PARSER = os.path.join(_REPO, "reference", "cpython", "Parser")
sys.path.insert(0, _CPY_PARSER)

import asdl  # noqa: E402  (from reference/cpython/Parser)

ASDL_PATH = os.path.join(_REPO, "reference", "cpython", "Parser", "Python.asdl")
OUT_PATH = os.path.join(_REPO, "jac-py", "jacpython", "ast_nodes.jac")

BUILTIN = {
    "identifier": "str",
    "string": "str",
    "int": "int",
    "constant": "PyObj",
}


def jac_type(field: asdl.Field) -> str:
    """Render one ASDL field's Jac type annotation."""
    base = BUILTIN.get(field.type, field.type)
    if field.seq:
        # `?*` (e.g. Dict keys, kw_defaults): list elements may be None.
        opt_elem = asdl.Quantifier.OPTIONAL in (field.quantifiers or [])
        elem = f"{base} | None" if opt_elem else base
        return f"list[{elem}]"
    if field.opt:
        return f"{base} | None"
    return base


def emit_fields(fields, out: list[str], *, base_locations: bool = False) -> None:
    for index, field in enumerate(fields):
        field_type = jac_type(field)
        if base_locations and field.name in {"end_lineno", "end_col_offset"}:
            field_type = "int | None"
        prefix = "    has " if index == 0 else "        "
        suffix = ";" if index == len(fields) - 1 else ","
        field_name = "`test" if field.name == "test" else field.name
        out.append(f"{prefix}{field_name}: {field_type}{suffix}")


def emit_obj(
    name: str, base: str | None, fields, out: list[str], *, base_locations: bool = False
) -> None:
    head = f"obj {name}({base})" if base else f"obj {name}"
    if not fields:
        out.append(f"{head} {{}}")
        out.append("")
        return
    out.append(f"{head} {{")
    emit_fields(fields, out, base_locations=base_locations)
    out.append("}")
    out.append("")


def generate(mod: asdl.Module) -> str:
    out: list[str] = []
    out.append('"""jacpython AST node archetypes.')
    out.append("")
    out.append("GENERATED by jac-py/tools/asdl2jac.py from reference/cpython/Parser/Python.asdl")
    out.append("(CPython pin: see tools/fetch_cpython_reference.py). Do not edit by hand.")
    out.append('"""')
    out.append("")
    # `constant` fields hold literal values as leaf objects, so pull in PyObj.
    out.append("import from objects { PyObj }")
    out.append("")
    # Single shared root: every AST archetype subclasses it, so parser memo
    # tables and generic node-holding seams type against one root.
    out.append("obj ast_node {}")
    out.append("")

    for dfn in mod.dfns:
        name = dfn.name
        val = dfn.value
        if isinstance(val, asdl.Sum):
            # Base type for the sum, then one archetype per constructor.
            out.append(f"# --- {name} ---")
            # Compiler visitors access these fields through the sum base.
            # Preserve the declarations used by the checked-in runtime model.
            base_fields = list(val.attributes)
            if name == "excepthandler":
                base_fields = list(val.types[0].fields) + base_fields
            elif name == "type_param":
                base_fields = [val.types[0].fields[0]] + base_fields
            emit_obj(name, "ast_node", base_fields, out, base_locations=True)
            for cons in val.types:
                emit_obj(cons.name, name, list(cons.fields) + list(val.attributes), out)
        elif isinstance(val, asdl.Product):
            out.append(f"# --- {name} (product) ---")
            emit_obj(name, "ast_node", list(val.fields) + list(val.attributes), out)
        else:  # pragma: no cover - ASDL has only Sum/Product
            raise TypeError(f"unexpected ASDL value for {name}: {type(val)!r}")

    return "\n".join(out).rstrip() + "\n"


def main(argv: list[str]) -> int:
    mod = asdl.parse(ASDL_PATH)
    if not asdl.check(mod):
        print("asdl.check failed", file=sys.stderr)
        return 1
    text = generate(mod)
    if "--stdout" in argv:
        sys.stdout.write(text)
        return 0
    n_nodes = text.count("\nobj ") + text.startswith("obj ")
    if "--check" in argv:
        # Drift guard: fail if the checked-in file differs from a fresh emit.
        try:
            with open(OUT_PATH) as fh:
                on_disk = fh.read()
        except FileNotFoundError:
            print(f"{OUT_PATH} missing; run asdl2jac.py to generate it", file=sys.stderr)
            return 1
        if on_disk != text:
            print(f"{OUT_PATH} is stale; regenerate with asdl2jac.py", file=sys.stderr)
            return 1
        print(f"{OUT_PATH} up to date ({n_nodes} archetypes)")
        return 0
    with open(OUT_PATH, "w") as fh:
        fh.write(text)
    print(f"wrote {OUT_PATH} ({n_nodes} archetypes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
